name: Wake Up Sports Spaces

on:
  schedule:
    # Runs every 3 hours (00:00, 03:00, 06:00, etc.)
    - cron: '0 */3 * * *'
  # Allows you to trigger it manually from the GitHub Actions tab
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping All 4 Spaces
        run: |
          URLS=(
            "https://sidimadtv-pro-snrt.hf.space"
            "https://sidimadtv-pro-alkass.hf.space"
            "https://sidimadtv-pro-ksa.hf.space"
            "https://sidimadtv-pro-dubai.hf.space"
           "https://sidimadtv-cors-proxy.hf.space"
            "https://sidimadtv-cdrm.hf.space"
            "https://sidimdd-cdrm.hf.space"
          )
          for url in "${URLS[@]}"; do
            echo "Checking $url..."
            # -I fetches headers only (fast), -s is silent, head -n 1 shows the status code
            curl -Is "$url" | head -n 1
          done
